<script id="expirationAdjustmentDialogTemplate" type="text/x-jsrender">
    <div id="expirationAdjustmentDialog" title="Adjust Expiration Date">
        <p>Adjust the expiration by setting an offset value. The number of days will be added or withdrawn from the current expiration day.</p>
        <p>for example -7 days to shorten with a week</p>

        <input id="adjustedDateSetter" type="number" />

    </div>
</script>